version: 2
branches:
    only:
      - development
environment:
  - MONGO_URI: mongodb://localhost:27017/test
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run:
      #   command: npm run e2e
      #   environment:
      #     MONGO_URI: mongodb://localhost:27017/test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Development to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git development:master


# HEROKU_APP_NAME
# HEROKU_API_KEY
# MONGO_URI
# PORT