version: 2
branches:
    only:
      - development
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:latest
      environment:
          MONGO_URI: mongodb://localhost:27017/test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
        command: npm run e2e
        