version: 2
branches:
    only:
      - development
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: 
        environment:
          - MONGO_URI: 'mongodb://localhost:27017/test'
        command: npm run e2e