version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:latest
  branches:
    only:
      - development
  environment:
    - MONGO_URI: 'mongodb://localhost:27017/test'

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run e2e